name: QA

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate Cache Key
        id: cache-key
        run: echo "value=$(sha256sum uv.lock | cut -d ' ' -f1)" >> "$GITHUB_OUTPUT"

      - name: UV Setup
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Sync Dependencies
        run: uv sync --all-extras --dev

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: UV Setup
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Restore Dependencies from Cache
        run: uv sync --all-extras --dev

      - name: Run Ruff
        run: uv run ruff check --output-format=github .

  test:
    name: Testing
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: UV Setup
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Restore Dependencies from Cache
        run: uv sync --all-extras --dev

      - name: Run Tests
        run: uv run pytest tests
